baseURL = "https://t6z.me/"
languageCode = "en-us"
title = "Thomas' Website"
theme = "lugo"

[params]
 relatedtext = "Related"
 favicon = "/images/favicon.ico"
 
 #list items
 datesinlist = true 
 authorsinlist = true
 
 #footer items
 nextprev = true
 taglist = true
 showrss = true
